### PR TITLE
feat: search notes when searching through contacts

### PR DESCRIPTION
**Pull request by iloveitaly**
This adds support for searching through notes [as explained here](https://github.com/monicahq/monica/issues/5079). There are already tests for the contact search helper, but let me know if you feel like this functionality needs a dedicated test.

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Create your PR as draft if it is not final yet. Mark it as ready... when it’s ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/readme.md#conventional-commits) that the project follows.

#### Backend/models changes
- [x] The API has been updated.
- [x] API's documentation has been added by submitting a pull request in the [marketing website repository](https://github.com/monicahq/marketing_site/pulls).
- [x] Tests have been added for the new code.
- [x] If you change a model, make sure the SetupTest file is updated. We need seeders to develop locally and generate fake data.

#### Other tasks
- [x] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG.md) entry added, if necessary, under `UNRELEASED`.
- [x] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [x] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [x] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by asbiin** [comment]
Thank you @iloveitaly that's nice.
We'll definitely need a test for that feature!

**Comment by iloveitaly** [comment]
@asbiin cool, I'll add a test for this. Thoughts on also searching through introduction notes as well? I'd like to add that as well in this PR if that works for you.

**Comment by iloveitaly** [comment]
@asbiin added tests and search on introduction text!

**Comment by asbiin** [comment]
Thanks @iloveitaly !

**Comment by OctoberMedia** [comment]
Great improvement Thanks to Iloveitaly. I'm curious as to how hard it would be to expand the search capability to include Activities (or for that matter, any of the other fields), As an example I played golf with 4 people at XYZ course. This is captured in the Activities field . It would really helpful to be able to search Activiteis, so we can get to a list of all contacts who were at that event

**Comment by OctoberMedia** [comment]
@iloveitaly Not sure how best to add the following to your work. But I have added the ability to search on Conversations, Phone call content and Activity summary and descriptions.

Is there a way you can add this to your efforts?

contact.php

    /** Added by Paul for Call content
     * Scope a query to include contacts whose phone calls contain the search phrase.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeCalls($query, int $accountId = null, string $needle)
    {
        return $query->orWhereHas('calls', function ($query) use ($accountId, $needle) {
            return $query->where([
                ['account_id', $accountId],
                ['content', 'like', "%$needle%"],
            ]);
        });
    }

    /** Added by Paul for messages
     * Scope a query to include contacts whose phone calls contain the search phrase.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeMessages($query, int $accountId = null, string $needle)
    {
        return $query->orWhereHas('messages', function ($query) use ($accountId, $needle) {
            return $query->where([
                ['account_id', $accountId],
                ['content', 'like', "%$needle%"],
            ]);
        });
    }
 
    /** Added by Paul for Actions description and Summary
     * Scope a query to include contacts whose action description or summary contain the search phrase.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeActionsum($query, int $accountId = null, string $needle)
    {
        return $query->orWhereHas('activities', function ($query) use ($accountId, $needle) {
            return $query->where([
               
                ['summary', 'like', "%$needle%"],
            ]);
        });
    }
    public function scopeActiondes($query, int $accountId = null, string $needle)
    {
        return $query->orWhereHas('activities', function ($query) use ($accountId, $needle) {
            return $query->where([
               
                ['description', 'like', "%$needle%"],
            ]);
        });
    }


searchHelper.php
        return Contact::search($needle, $accountId, $orderByColumn, $orderByDirection)
            ->notes($accountId, $needle)
	    ->calls($accountId, $needle)
	    ->messages($accountId, $needle)
	    ->actionsum($accountId, $needle)
	    ->actiondes($accountId, $needle)
            ->introductionAdditionalInformation($needle)
            ->addressBook($accountId, $addressBookName);

**Comment by OctoberMedia** [comment]
I have added a PR to expand on @iloveitaly search. The new PR includes search on conversations, phone calls and both the summary and description in a an activity

**Comment by djaiss** [comment]
Unfortunately this is causing huge issues in production. We have to disable it until we find a fix.

**Pull request merged**
