### PR TITLE
chore: fix vuejs v-if and v-else usages

### PR DESCRIPTION
**Pull request by asbiin**
This should not modify any feature

### CODE REVIEW

**Comment by djaiss** [comment]
@asbiin this is a dangerous change. We need to test it thoroughly for each one of those changes. I’ll help you testing that. Because I’m sure we’ve broken some stuff here.

**Comment by asbiin** [comment]
@djaiss it's [pure vuejs logic](https://fr.vuejs.org/v2/guide/conditional.html). Don't you believe it can works? ;)

**Comment by djaiss** [comment]
@asbiin two errors on Cypress 😀

One in Activity Types in the Settings, the other when managing a task.

I don't have time tonight but I can help to check what's going on.

**Comment by asbiin** [comment]
@djaiss I also had bizarre error in adding a life event...

**Pull request merged**
