### PR TITLE
[proposal] responsiveness fix + display image on contact list

### PR DESCRIPTION
**Pull request by jeremydenoun**
After a tour between mobile/tablet/desktop browser, I propose some change on responsiveness for a better user experience.

Change Summary :

- Header menu responsive fix
- Content top margin more similar
- Adaptative Sidebar (better breakpoint)
- Add contact image picture on contact list

Please be free to make suggestions if needed

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks a lot for the PR.

We've just pushed a huge change in production - now this PR has conflicts. Can you fix them? Thanks a lot!

**Comment by jeremydenoun** [comment]
Done

**Comment by Nebucatnetzer** [comment]
Looks good to me :)

**Comment by djaiss** [comment]
Thanks for the PR, but I can't merge as is. It's more broken with your changes than before.

image

**Comment by jeremydenoun** [comment]
I can fix but we must chose what's the best for mobile view :
capture d ecran 2017-06-16 a 20 53 30

1. We allow long name and display entirely (but we must consider hide kids count)
1. We should wrap long name and fit with ellipsis

What do you prefer ?

**Comment by Nebucatnetzer** [comment]
This is interesting which browser are you're using @djaiss?

**Comment by djaiss** [comment]
@jeremydenoun Option 2. Wrap with ellipsis.

Thanks a lot.

**Comment by jeremydenoun** [comment]
@djaiss can you check again ? this should be better

**Pull request merged**
