### PR TITLE
feat(calendar): add Lunar Calendar support monicahq/monica#3355

### PR DESCRIPTION
**Pull request by naiba**
Hello, I spend two days to implement Lunar Calendar support.
It with some font-end changes. @djaiss 

**Add/Edit Contacts**

image

**Add/Edit Reminders**

image

*reopen to trigger azure ci*

### CODE REVIEW

**Comment by naiba** [comment]
@asbiin This PR has passed all tests and is ready to merge.
Added support for the Chinese lunar calendar date, which can remind the traditional Chinese people’s birthday on the lunar calendar. According to my understanding, Japan, South Korea, Thailand, and India have date notation similar to the Chinese lunar calendar. They can now be easily added.
The changes to the front end are relatively small, only two select elements are added. At the same time, there are no changes to the original API, which can be smoothly upgraded.

I am using vscode, and I have not found a code style formatting tool suitable for StyleCI, sorry :)

**Comment by asbiin** [comment]
@naiba ? I don't understand why you closed the PR, we can discuss it to see how to implement this?

**Comment by naiba** [comment]
> @naiba ? I don't understand why you closed the PR, we can discuss it to see how to implement this?

@asbiin because you don't give me any feedback in 5 days. I really need the lunar calendar, because my family uses this type it's useless without the lunar calendar.

I am very happy to re PR this again with the storage folder protection feature **if we need this**.

**Comment by djaiss** [comment]
@naiba thanks for submitting this PR.
@asbiin and I have very limited free time, and we were both on holidays during the last month. Please don't be discouraged by our lack of answers on your PR.

We'll review this PR and discuss it as @asbiin said, because it looks like it’s a very valuable contribution for cultures other than western ones - and therefore, we need to understand how this works before approving it. I’m really sorry for my lack of knowledge in this area.

**Comment by naiba** [comment]
@djaiss Thanks for your approval. If this PR looks good, please let me known, I'll handle the conflict and open another PR on Friday night or this weekend.

**Comment by naiba** [comment]
Any update?

**Comment by asbiin** [comment]
@naiba this PR is closed now, we need to reopen it, or recreate it to be able to work on it

**Comment by naiba** [comment]
> @naiba this PR is closed now, we need to reopen it, or recreate it to be able to work on it

It’s been too long since I last indicated that it can take time to re-initiate. You could have spent some time reviewing and then I re-initiated and then merged directly. As of now, re-initiating has become very difficult, and I will not spend time to resolve conflicts again and wait for review.

**Pull request closed without merging**
