### PR TITLE
Add/Delete activity types

### PR DESCRIPTION
**Pull request by mheap**
This PR allows users to create their own activity groups + activity types and is related to #346.

Instead of creating a whole UI for something that is likely to be infrequently used, I've implemented the functionality as `artisan` commands. There are instructions in `readme.md` how to use it under `Advanced Usage`, and I've recreated here to show how the commands can be used:

### Activities

You can change the activities shown in your Monica instance by creating your own
set of activity groups and activity types. To do this:

First, empty the existing actitivity list (*this will remove all activities from
your contacts. BE CAREFUL*):

```bash
php artisan monica:clear-activities
```

Next, register a new activity group:

```bash
php artisan monica:add-activity-group "My New Group"
```

Finally, add an activity type within that group:

```bash
php artisan monica:add-activity "Did Something" "location_type" "icon" "My New Group"
```

There are limited options available for `location_type` and `icon` due to existing design constraints:

`location_type`:
* `his_place`
* `my_place`
* `outside`

`icon`:
* `ate_his_place`
* `ate_home`
* `bar`
* `concert`
* `hang_out`
* `movie_home`
* `museum`
* `picknicked`
* `play`
* `restaurant`
* `sport`
* `talk_home`
* `theater`

The last thing to do is add translations for your new activities. The way
to do this is create a `resources/lang/<lang>/people.php` file, and add
some new keys for your new activities. They will be prefixed with either
`people.activity_type_group_` or `people.activity_type_`. *These will be deleted
each time you update Monica*

### Checklist

- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Make sure that the change you propose is the smallest possible.
- [x] Screenshots are included if the PR changes the UI.
- [ ] Tests added for this feature/bug.
- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [x] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [x] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks @mheap 

I won't merge this immediately because I'm finishing the API and I don't want to add another layer in complexity for shipping the API. I'll be here right after though! Thanks!

**Comment by djaiss** [comment]
I'm sorry for all the time it takes me to review this and add it to the repository. First of all thanks so much for all this hard work.

I actually wonder if we should do this in the command line, or if I should add it inside the UI entirely. To be honest I'm considering the second route: letting users change the activity types (or add them) at their leisure. I'll actually do this in a future version, and when I'll do it, this code will be invalid.
What do you think about this?

**Comment by mheap** [comment]
No problem!

I agree that it'd be best with a real UI but creating commands was the quickest solution for me on my local install. Feel free to merge and remove later, or close and implement the UI instead :)

**Comment by djaiss** [comment]
@mheap I can finally close this PR 😀We now have the feature backed in Monica itself, let me know if you find it useful.

And thanks again for all your work there.

**Pull request closed without merging**
