### PR TITLE
feat: quick add with email

### PR DESCRIPTION
**Pull request by iloveitaly**
https://github.com/monicahq/monica/issues/5083

Not sure if it's worth writing a test for this case, feel free to point me to an existing one for the quick add parsing and I can update it.

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Create your PR as draft if it is not final yet. Mark it as ready... when it’s ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/readme.md#conventional-commits) that the project follows.

### Front-end changes
- [x] If you change the UI, make sure to ask repositories administrators first about your changes by pinging djaiss or asbiin in this PR.
- [x] Screenshots are included if the PR changes the UI.
- [x] Front-end tests have been written with Cypress.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@asbiin this one is ready to go! Want to take a look?

**Comment by asbiin** [comment]
@iloveitaly I think that's a good idea, however we need to be sure it does downgrade search performances. Is there a index on email on the contacts table?

**Comment by iloveitaly** [comment]
@asbiin Doesn't look like it

image

Any issue with adding an index to this table?

**Comment by asbiin** [comment]
@iloveitaly no, we should add it, that's the idea.

**Comment by asbiin** [comment]
@iloveitaly don't hesitate if you need help about adding the index

**Comment by asbiin** [comment]
Thank you @iloveitaly

**Comment by iloveitaly** [comment]
@asbiin no problem!! So glad this got merged. One improvement that would be great here is to detect an email-only search entry and use that value for the email field instead of the first name field.

**Pull request merged**
