### PR TITLE
feat: Add a confirmation to delete a journal entry #4308

### PR DESCRIPTION
**Pull request by simonardejr**
Implementing the native confirmation dialog when click on `delete` on journal entries list. This was requested on #4308

### CODE REVIEW

**Review by asbiin — CHANGES_REQUESTED** [review]
Thank you @simonardejr 
However, we don't use `confirm` function anymore. See usage of the `confirm` component (`<confirm>`) in some resource blade files.

**Comment by simonardejr** [comment]
Ah, ok! give me some minutes and I'll update this :grin:

**Comment by simonardejr** [comment]
Don't know if I've done everything right (fetching, merge, and stuff), but let me know if I need to do anything else :grin:

**Comment by asbiin** [comment]
Perfect @simonardejr :+1: 
And thanks also @TeddyBear06  ;)

**Pull request merged**
