### PR TITLE
fix: filter by escaped tagname

### PR DESCRIPTION
**Pull request by oliverpool**
_Fixes #3469_ 

As discussed in the issue, the tag filter will now use the URL-escaped name of the tag, using a new get parameter: `tagnames` (usage as array: `tagnames[]=my_tag`).

I would recommend removing the `tagX` parameters, but I don't know how much backward-compatibility should be kept. Hence I just marked it as `DEPRECATED` in the code.

I updated the `index.blade.php` view to use this new system.
As well as the `Tags.vue` file (I took the liberty of tweaking the HTML, to make a real link instead of a span+onclick):
image
(the hover will make a blue background, like all the links in Monica).

---
- [ ] Front-end tests have been written with Cypress.
=> is it needed here?

- [x] Tests have been added for the new code.

- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG.md) entry added, if necessary, under `UNRELEASED`.
=> it will be added automatically on release I guess, no?

- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
=> not necessary yet I think

### CODE REVIEW

**Comment by oliverpool** [comment]
I really like this project.
However I am sorry, but I can't sign your CLA.

https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

Further details: https://github.com/hasura/graphql-engine/pull/5323#issuecomment-655665033

**Comment by oliverpool** [comment]
Further input regarding "The Developer Certificate of Origin":  https://drewdevault.com/2021/04/12/DCO.html

**Comment by asbiin** [comment]
@oliverpool I understand your concern regarding our CLA, but right now this is how we manage this repository. Can you please reconsider signing the CLA, or we will not be able to merge this PR?

**Comment by oliverpool** [comment]
@asbiin I would as an exception accept to sign the CLA for this PR only.

However as far as I know, there is no way to limit the CLA signature to a specific PR.

 https://github.com/cla-assistant/cla-assistant/issues/18 even indicates that they do not want to let users to "view all signed CLAs and to revoke CLAs for future pull requests."

**Comment by asbiin** [comment]
I'm closing this PR after some times.
Another solution has been implemented.

**Pull request closed without merging**
