### PR TITLE
ci: add initial Laravel Psalm plugin

### PR DESCRIPTION
**Pull request by muglug**
This adds a Laravel plugin for Psalm that improves Psalm's ability to infer types when using Laravel functions and methods.

### CODE REVIEW

**Comment by asbiin** [comment]
Thanks @muglug 
That's nice, but psalm didn't run with this conf:
```
Scanning files...

In Config.php line 886:
                                                    
  Failed to load plugin Psalm\LaravelPlugin\Plugin  
                                                    

In BroadcastManager.php line 211:
                                   
  Class 'Pusher\Pusher' not found  
```
(and the program exited with code 0!)

**Comment by muglug** [comment]
@asbiin I was able to fix that by adding `BROADCAST_DRIVER=log` to my local `.env`. Alternatively I can add `pusher/pusher-php-server` as a dev dependency.

**Comment by asbiin** [comment]
@muglug I've added BROADCAST_DRIVER to the env file, it works well

**Comment by asbiin** [comment]
Thank you for your help @muglug !

**Comment by muglug** [comment]
You’re welcome!

**Pull request merged**
