### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by InverterOfControl**
I added a german translation.

### CODE REVIEW

**Comment by aejnsn** [comment]
Do you care if I have this reviewed by another German speaker and report back?

**Comment by InverterOfControl** [comment]
Of course not. Feel free to find my mistakes. We could also have two versions. One for each polite form ("Sie", "Du"). I decided to use "Du" throughout the translation.

**Comment by aejnsn** [comment]
Awesome. What do other software packages use for their form in German translations?

**Comment by InverterOfControl** [comment]
Well Facebook and Twitter etc do use the informal variant and I had the feeling this would suit monica. But maybe I am wrong and the formal variant would have been better.

**Comment by aejnsn** [comment]
I had my German speaker check it out. Looks good to him. :smile:

**Comment by djaiss** [comment]
This brings me a lot of joy. Thanks a lot for your help!

**Pull request merged**
