### PR TITLE
Add end 2 end frontend testing with Cypress

### PR DESCRIPTION
**Pull request by djaiss**
We already have end 2 end testing with Laravel Dusk for 2-3 features. The problem with Dusk is the fact that it's not super user friendly and a bit hard to setup locally.

[Cypress](https://www.cypress.io/), which is MIT, is an awesome tool made just for this. It's like Dusk, but
* not based on Selenium which makes tests super fast
* has an awesome CLI and an even awesomer GUI to debug
* integrate well with CI
* it can even take screenshots or record a video of the run so you can see where it went wrong

There are two new commands:
- `yarn run e2e` to run the front end tests through the CLI (headless browser)
- `yarn run e2e-gui` to run the tests through a GUI (normal browser - mostly for debugging purposes)

image

image

#### Other tasks
- [x] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [x] Implement this in CircleCI

### CODE REVIEW

**Comment by djaiss** [comment]
@asbiin could you check how to put this in [CircleCI](https://docs.cypress.io/guides/guides/continuous-integration.html#CircleCI) ?

**Comment by tomzx** [comment]
See https://docs.cypress.io/guides/guides/continuous-integration.html#CircleCI.

**Comment by asbiin** [comment]
@djaiss OK I think I have finished here: tests are running in CircleCI, producing junit results file, which are showed up in circleci. A cypress dashboard exists for monica, here: https://dashboard.cypress.io/#/projects/2i96ir/runs where you can found the results.
BTW, currently your tests are broken.

**Comment by asbiin** [comment]
@djaiss OK tests are running now. BTW your tests take 14min !!!

**Comment by djaiss** [comment]
> OK tests are running now. BTW your tests take 14min !!!

"your" tests. Our tests! It's our common effort ;-)

**Pull request merged**
