### PR TITLE
feat: add Vietnamese language

### PR DESCRIPTION
**Pull request by nhymxu**
Translate 95%. Some emotion string will translate soon
image

### CODE REVIEW

**Comment by asbiin** [comment]
Thank you @nhymxu I will review the translation ASAP as well.
I already see 1 glitch: I think in Vietnamese there is no plural form (all ":count contact|:count contacts" source text). In that case you don't have to add a plural form in the translated text, ex: ":count contact|:count contacts" => ":count liên hệ".
It's based on a laravel code, and you can also see [here](https://github.com/monicahq/monica/blob/139d53cef7e31a51b2c2f39999492fa9a2ed63e4/resources/js/pluralization.js#L50) it's included in Monica.

**Comment by nhymxu** [comment]
@asbiin 
Thank you, I will update this on crowdin when see this source text

**Comment by asbiin** [comment]
@nhymxu actually I have validated all other translations, you can see all not approved text in crowdin: https://crowdin.com/translate/monicahq/12/en-vi?filter=basic&value=5 (select others files too)

**Comment by nhymxu** [comment]
@asbiin 
I updated some string. Except `every day|every :number days` will translate difference for singular `hàng ngày` and plural `mỗi :number ngày`.
Rule same with `month` and `year`

**Comment by asbiin** [comment]
@nhymxu That's amasing, thank you! For `every day|every :number days` and alike, you'll still have to define a unique form, because only the 1st item will be rendered very time. For instance, this text will always be translated as `hàng ngày`, no matter the number of days ... which is not what we want. I agree it's not exactly the same text, well that's the problem with translations: some times we have to deal with it.

**Pull request merged**
