### PR TITLE
Reordered countries seed by ISO code to improve readability

### PR DESCRIPTION
**Pull request by colourgarden**

### CODE REVIEW

**Comment by djaiss** [comment]
Tests fail because we've changed the order of the seeder. The test is definitely not robust enough.

**Comment by Phrohdoh** [comment]
How does a reorder improve readability?

**Comment by colourgarden** [comment]
Maybe digestibility would be a better description. If this list needs to be edited again in the future, it's easier to navigate if the countries are ordered.

**Comment by djaiss** [comment]
Thank you very much for this PR. The test is still failing, so I'll close the PR because of the lack of activity.

**Pull request closed without merging**
