### PR TITLE
feat: add support for maiden names [wip]

### PR DESCRIPTION
**Pull request by tbirrell**
Per #2152, here is the beginning of the work for maiden name support.

I wanted to make the Maiden Name field toggle based on the Gender, but aside from Monica, I have no experience with Vue and couldn't figure it out. And since custom genders are supported now, it might not be worth trying to pick and choose.

Aside from adding in maiden names, the only other change was moving nicknames down to a new row. This was for two reasons. First, so it could fit. And second, so that when we eventually add the middle name field, it can also fit.

This is what the current edit form looks like

screenshot-monica tapl io-2018 12 17-12-10-42

I'm not sure what tests, if any, you want for this. I tried to find other tests for adding a DB field, but couldn't. So if you could point me in the right direction, that would be appreciated.

If anyone else wants to contribute, I am fine with this.
Remaining work includes:

- [x] Saving maiden names
- [ ] Writing Tests (see above)

### CODE REVIEW

**Comment by tbirrell** [comment]
I'm not sure why circleci is still failing with:

```
Monica asset are not up to date.
Please update the Monica assets yourself by running:
 ~ php artisan lang:generate
 ~ yarn run production
Exited with code 2
```

I've run both those commands.

**Comment by asbiin** [comment]
"Maiden" is only for women, right?
It would be more interesting to have a solution for everyone, like "birth name"?

**Comment by tbirrell** [comment]
@asbiin, I have responded to your comments over in [the issue](https://github.com/monicahq/monica/issues/2152#issuecomment-448268791).

**Comment by tbirrell** [comment]
Regarding the discussion in #2152, it seems as if we will be wanting to go a slightly different route for this. If you want to use this code in the interim, that's fine by me. Otherwise, we should probably close this PR.

**Pull request closed without merging**
