### PR TITLE
Add .htaccess

### PR DESCRIPTION
**Pull request by erdmenchen**
See #97.
Just added the .htaccess file as it is provided with laravel.

### CODE REVIEW

**Comment by enko** [comment]
I would vote against this PR, because this is specific to apache and apache is not so wide spread any more that it justifies to put this file here. I think it would be a better approach to put this into some installation instructions.

**Comment by erdmenchen** [comment]
Why? Installation is already complicated enough and not well documented. 
Since this file is just shipped with Laravel, which this project is based on, I cannot understand why it was removed in the first place.
Also web.config is present, too.

See source: https://github.com/laravel/laravel/blob/master/public/.htaccess

**Comment by peterbrinck** [comment]
I must agree with @erdmenchen 

It's a weird thing to leave out `.htaccess`.
Apache is STILL wide spread and used on many servers.

**Comment by djaiss** [comment]
@erdmenchen honestly I don't know why it was removed. I don't remember - perhaps when it was hosted on Heroku? ¯\_(ツ)_/¯

**Comment by adrum** [comment]
@enko What are the negative side effects of including this? I think it’s a no brainer and just adds to the number of servers this project can deploy on. I created another PR for this because I didn’t see this original one and thought it’s a pretty trivial thing to add back into the project.

**Comment by djaiss** [comment]
Before I merge this (because I agree that Apache should be equally supported), as I run Nginx in production, do you think it's possible that it causes problem, and should I do something about this in production - or won't it have any impact in production whatsoever?

**Comment by adrum** [comment]
I think the side effect would be other server types (nginx) would server the .htaccess file if someone requested it. We would add a change in the nginx config to deny access to hidden files, or just .htaccess if needed. Unless I'm completely missing something.

**Comment by erdmenchen** [comment]
@djaiss  the Laravel framework has the same files in place. so there is no need to fear any problems...

**Comment by djaiss** [comment]
Thanks for this PR!

**Comment by Bibabidu** [comment]
Hey, I'm not sure this is the right place to discuss my question but I've encountered a problem related to the .htaccess-file. My redirect didn't work properly so I tinkered a bit with the rule. The following configuration works for me:

Original: `RewriteRule ^ index.php [L]`
New Rule: `RewriteRule ^(.*)$ /index.php?/$1 [L]`

Can someone, with a better understanding of .htaccess, tell me, if this is an unique issue only faced by me? Can my fix possibly cause any problems with using monica?

Thanks a lot already!

**Comment by asbiin** [comment]
@Bibabidu this is the default .htaccess file for all Laravel sites. See https://github.com/laravel/laravel/blob/master/public/.htaccess

**Pull request merged**
