### PR TITLE
composer: require at least PHP 7.0

### PR DESCRIPTION
**Pull request by TomasVotruba**
As PHP 5.6 was dropped here
https://github.com/monicahq/monica/commit/53bb6ff7b730b598ad8e25d09b601b198ef1b8ac

### CODE REVIEW

**Comment by djaiss** [comment]
@kstrauser would this have an impact on what you've done with Docker?

**Comment by kstrauser** [comment]
No. The Docker image uses 7.0.

**Comment by djaiss** [comment]
Thanks a lot for this PR.

**Comment by TomasVotruba** [comment]
Thank you!

**Pull request merged**
