### PR TITLE
feat: Allow editing middle name

### PR DESCRIPTION
**Pull request by ivankruchkoff**
First of all thanks so much for taking the time to open a pull request and help the project. It's because of people like you that we love working on this project.

Please read the list below. Feel free to delete this text after but we need you to read it so we make sure that the project is consistent and remains of quality.

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [ ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [ ] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/index.md#conventional-commits) that the project follows.

### Front-end changes
- [ ] If you change the UI, make sure to ask repositories administrators first about your changes by pinging @djaiss or @asbiin in this PR.
- [x] Screenshots are included if the PR changes the UI.
- [ ] Front-end tests have been written with Cypress.

#### Backend/models changes
- [ ] The API has been updated.
- [ ] API's documentation has been added by submitting a pull request in the [marketing website repository](https://github.com/monicahq/marketing_site/pulls).
- [ ] Tests have been added for the new code.
- [ ] If you change a model, make sure the FakeContentTableSeeder is updated. We need seeders to develop locally and generate fake data.

#### If the code changes the SQL schema
- [ ] Make sure exporting account data as SQL is still working.
- [ ] Make sure your changes do not break importing data with `vCard` and `.csv` files.
- [ ] Make sure account reset and deletion still work.

#### Other tasks
- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG.md) entry added, if necessary, under `UNRELEASED`.
- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [ ] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [ ] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by ivankruchkoff** [comment]
Addresses #511

**Comment by ivankruchkoff** [comment]
Added field in contact:
/people/add
/people/h:HASHID/edit

Screenshot 2019-11-17 11 27 21
Screenshot 2019-11-17 11 17 37

**Comment by ivankruchkoff** [comment]
Hi @asbiin any tips for getting this reviewed/merged?

**Comment by asbiin** [comment]
@ivankruchkoff thank you for your time and fix.
Here you need to add some test to address the minimum code coverage (60%). But the function should already have been covered!

**Comment by asbiin** [comment]
@ivankruchkoff I've added the test, it's ok now! Should you sign the CLA please?

**Comment by ivankruchkoff** [comment]
@asbiin I've signed the CLA, but it just redirects me back to this PR without updating the status

Screenshot 2020-01-02 14 50 47

I confirm that:

I have the legal authority to enter into this Agreement.
My contribution is either your original creation, based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and you have the right under that license to submit that work with modifications, whether created in whole or in part by you, or you have clearly identified the source of the contribution and any license or other restriction (like related patents, trademarks, and license agreements) of which you are personally aware.
The grant of rights under Section 2 does not violate any grant of rights which I have made to third parties, including my employer. 
I submit to https://github.com/monicahq/monica/blob/master/CODE_OF_CONDUCT.md

**Comment by cayblood** [comment]
Please get this in! Got some vcard imports that are showing up wrong without it.

**Comment by ivankruchkoff** [comment]
Merged latest master branch cc @asbiin

**Comment by asbiin** [comment]
@ivankruchkoff thank you for your help!

**Pull request merged**
