### PR TITLE
Fix issues found by static analysis

### PR DESCRIPTION
**Pull request by muglug**
This PR fixes typos/ommissions found by a static analysis tool I made. To find these issues, I had to strip out the Laravel aliases (done [in a separate branch](https://github.com/monicahq/monica/compare/master...muglug:remove-aliases)).

[Here's the config](https://github.com/muglug/monica/commit/e0aa4fbfc0bca17def4ebad17933a670916213d7) that I used to ignore pretty much everything the tool warned about, except `UndefinedClass`, `InvalidMethodCall` and `NullReturnStatement`.

### CODE REVIEW

**Comment by muglug** [comment]
@asbiin it's called [Psalm](https://github.com/vimeo/psalm). Once you merge this PR I can open up another to add it to the Travis builds, and you can choose what to improve incrementally.

**Comment by asbiin** [comment]
@muglug I like your approach ! Can you fix StyleCI so we can merge this PR ? Thanks.

**Comment by muglug** [comment]
I've fixed the styleci issues - `length_ordered_imports` was a new one...

**Comment by asbiin** [comment]
@muglug if you want, I invite you to add you in the CONTRIBUTORS file

**Comment by asbiin** [comment]
Thank you @muglug !

**Pull request merged**
