### PR TITLE
style: align birthday reminder checkbox

### LINKED ISSUE #3904: "Create an annual reminder for their birthday" checkbox is misaligned
image

### PR DESCRIPTION
**Pull request by rbuch**
Fixes #3904.

UI change, so pinging @djaiss.

image

### CODE REVIEW

**Review by asbiin — APPROVED** [review]

**Comment by djaiss** [comment]
Thanks so much!

**Comment by djaiss** [comment]
@asbiin i don’t understand why the CI doesn't work here. Any ideas?

**Comment by asbiin** [comment]
@djaiss in fact the CI is working perfectly, but it reuquires to rebuild the assets and publish them!

**Comment by djaiss** [comment]
Thanks @asbiin

**Pull request merged**
