### PR TITLE
Removed --no-suggest option from composer

### PR DESCRIPTION
**Pull request by tomgs**
The option does not exist.

### CODE REVIEW

**Comment by asbiin** [comment]
@tomgs Thank you for this suggestion.
But ... it exists:
https://getcomposer.org/doc/03-cli.md#install-i
Should we keep it? That's another story.

**Comment by tomgs** [comment]
Alright, so it's a version thing. The version installed by default from the ubuntu repo is outdated and does not contain that option. Should we force the user to get the latest composer, or at least one that contains that option?

**Comment by asbiin** [comment]
Is there an error with this old version?
The option is only display with `composer install --help`.

**Comment by tomgs** [comment]
I've just received it when trying to install composer....

**Comment by asbiin** [comment]
Maybe we can suggest to update composer before installing packages instead?

**Comment by tomgs** [comment]
Yeah, probably the right way to go.

**Comment by djaiss** [comment]
Should we do something more here then?

**Comment by tomgs** [comment]
Delete this, as a person coming with a clean install will probably not see the error. It's on me for using an outdated version.

**Pull request closed without merging**
