### PR TITLE
feat: 3513 add Pronouns

### LINKED ISSUE #3513: Add Preferred Pronouns
As gender identify becomes more fluid, it might be nice to be able to track preferred pronouns for people who choose something non-default.  It could be tracked as notes, but it might also be nice to have a dedicated field for this, perhaps using the current "gender" tracking for the defaults for a specific pronoun.

### PR DESCRIPTION
**Pull request by Kotarosz727**
@djaiss 
UI Change as below. New pronouns input field is also added to people edit, relationship crate page.
image

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/main/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Create your PR as draft if it is not final yet. Mark it as ready... when it’s ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/main/docs/contribute/readme.md#conventional-commits) that the project follows.

### Front-end changes
- [x] If you change the UI, make sure to ask repositories administrators first about your changes by pinging djaiss or asbiin in this PR.
- [x] Screenshots are included if the PR changes the UI.
- [x] Front-end tests have been written with Cypress.

#### Backend/models changes
- [x] The API has been updated.
- [x] API's documentation has been added by submitting a pull request in the [marketing website repository](https://github.com/monicahq/marketing_site/pulls).
- [x] Tests have been added for the new code.

#### If the code changes the SQL schema
- [x] Make sure exporting account data as SQL is still working.
- [x] Make sure your changes do not break importing data with `vCard` and `.csv` files.
- [x] Make sure account reset and deletion still work.

resolve #3513

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Ideally this would be prepopulated based on the gender selected above (with default pronouns for each gender configurable when defining them). I'm not sure how feasible that is though :)

**Comment by puppycodes** [comment]
> Ideally this would be prepopulated based on the gender selected above (with default pronouns for each gender configurable when defining them). I'm not sure how feasible that is though :)

I believe the less assumptions made in this section the better. Gender and pronouns do not necessarily have a relationship to one another. The analogy I would draw here would be trying to infer the gender from someones first name, which would be a bad idea because of the degree of variation and the fact that they are not necessarily connected. I believe the most inclusive tactic is to simply allow these both of these fields (gender and pronouns) to be treated like basic strings, allowing for any entry. This would be a future proof and maximally inclusive and also happens to simplify the dependencies.

**Comment by pmlandwehr** [comment]
Would it be possible to default family relations to "sibling", "parent", etc. when gender is unknown?

**Comment by puppycodes** [comment]
> Would it be possible to default family relations to "sibling", "parent", "spouse", etc. when gender is unknown?

+1 good call

**Comment by asbiin** [comment]
This needs more work, and we don't accept more changes in the `4.x` branch. Don't hesitate to reopen it on the `main` branch if that makes sense.

**Pull request closed without merging**
