### PR TITLE
Feature/docker updates

### PR DESCRIPTION
**Pull request by kstrauser**
This fixes two Docker problems with the 0.7.x versions:

- It adds the new `php7-simplexml` dependent package
- It updates `docker/test-server.sh` so that `artisan key:generate` and `artisan db:seed *` don't hang while waiting for operator input.

I used this to build (and push) the v0.7.0 and v0.7.1 Docker Hub images (and I'm running v0.7.1 with from that image locally).

### Checklist

- [X] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [X] If the PR is related to an issue or fix one, don't forget to indicate it.
- [X] Make sure that the change you propose is the smallest possible.
- [X] Screenshots are included if the PR changes the UI.
- [X] Tests added for this feature/bug.
- [X] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [X] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [X] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### CODE REVIEW

**Comment by djaiss** [comment]
Much ❤️  for your help. It's really appreciated.
The v1.0.0 is coming soon (it's already on master but not yet tagged). I don't think it's gonna change much the Dockerfile - I'll have to check when I'll tag the version.

**Comment by kstrauser** [comment]
After you tag it, I can always update and PR the Dockerfile as I upload the image.

BTW, do you know if there's an easy way to get notifications of new tags? I have a reminder set up for myself to check for new release, but I often forget to actually do it.

**Comment by djaiss** [comment]
> BTW, do you know if there's an easy way to get notifications of new tags? I have a reminder set up for myself to check for new release, but I often forget to actually do it.

@kstrauser that's a very good question. I don't know, and it sucks a little bit. Perhaps I could set up a newsletter for new releases like this.

**Comment by djaiss** [comment]
@kstrauser I've found one tool for this: https://about.sibbell.com/

It'll probably help you there 😀

**Pull request merged**
