### PR TITLE
docs: add Mailgun instructions

### PR DESCRIPTION
**Pull request by tomgs**
Just updating the Mailgun instructions for Heroku as per [this thread](https://github.com/monicahq/monica/issues/1776#issuecomment-419634131).

### CODE REVIEW

**Comment by asbiin** [comment]
I think the mailgun secret can be grab from this address: https://app.mailgun.com/app/account/security (`Private API Key` field).

**Comment by asbiin** [comment]
@tomgs Great job otherwise!

**Comment by tomgs** [comment]
Hey @asbiin I think that's what I wrote - is it not clear from the instructions?

**Comment by asbiin** [comment]
@tomgs you wrote
```
* Get your API key by following [these instructions](https://help.mailgun.com/hc/en-us/articles/203380100-Where-can-I-find-my-API-key-and-SMTP-credentials-).
```
I say we can help the user find the key by adding this link that display the link directly: https://app.mailgun.com/app/account/security

**Comment by asbiin** [comment]
Thanks @tomgs

**Pull request merged**
