### PR TITLE
docs: fix cloudron link to demo instance

### PR DESCRIPTION
**Pull request by gramakri**
We recently changed our demo instance URL to https://my.demo.cloudron.io

### CODE REVIEW

**Comment by asbiin** [comment]
Hi @gramakri ! Pleased to hear about you. I don't know how to reach you out, can you please review/merge my PR [here](https://git.cloudron.io/cloudron/monica-app/-/merge_requests/1) on cloudron monica-app?

**Comment by gramakri** [comment]
@asbiin Oh wow, that is pending for a year! Sorry about that, I wasn't even of that MR. Will look into it right away.

**Comment by gramakri** [comment]
@asbiin Merged and published a new package, thanks!

**Comment by asbiin** [comment]
Great! Thanks @gramakri :)

**Pull request merged**
