### PR TITLE
chore: add paratest for parallel tests [wip]

### PR DESCRIPTION
**Pull request by djaiss**
@asbiin check this out.

This reduces drastically the tests by running the tests in parallel with https://github.com/paratestphp/paratest (using `./vendor/bin/paratest` to run them). However by doing so, there is one deadlock.

### CODE REVIEW

**Comment by djaiss** [comment]
Lol it works here, but not locally because of deadlocks.

**Comment by djaiss** [comment]
Doh I'm stupid. It works because it ran phpunit, not paratests.

**Comment by asbiin** [comment]
It's really not working.
- there are a lot of Deadlock
- it cannot run only our 4 testsuites. it wants to run Dusk tests too ...

**Comment by djaiss** [comment]
That was just a try. Might be interesting to revisit in the future though.

**Pull request closed without merging**
