### PR TITLE
Fix for default accounts email confirmation in setup:test

### PR DESCRIPTION
**Pull request by jappareti**
First, I'm new to contributing to open source and to Laravel, so go easy 😸 I'm more experienced with front-end too, so most of my contributions won't be on the back-end. I'm excited about this project, I think it's awesome what you guys are doing!

This is my attempt at fixing #1433. I'm not sure if this is the most clean / efficient way of implementing - please let me know any suggestions!

### CODE REVIEW

**Comment by jappareti** [comment]
I'm not sure if I understand why the styleci check is failing. Is it because there's an extra line?

**Comment by asbiin** [comment]
@jappareti yes the extra line with only spaces is not allowed.
Just apply the patch from styleci : "download raw diff"

**Comment by djaiss** [comment]
@jappareti thanks a lot and congrats for this contribution 😀

**Comment by djaiss** [comment]
Congrats on your first PR @jappareti

**Pull request merged**
