### PR TITLE
docs: add developer linux setup info [wip]

### PR DESCRIPTION
**Pull request by tomgs**
Please do not merge yet, I'm adding docs stuff as I see them.

### CODE REVIEW

**Comment by asbiin** [comment]
@tomgs any news with this docs?

**Comment by tomgs** [comment]
Never got it running. Wanted to check out the docker one, didn't get around to it. If it's OK, please keep it open until I get around to it.

**Comment by asbiin** [comment]
Closing this for now. Don't hesite to reopen it when you're ready @tomgs !

**Comment by tomgs** [comment]
cleanup is good:)

*--------------------------------*
*Tom Granot-Scalosub*
*My Personal Site: KidOnPoint.com <https://kidonpoint.com>*
*My E-Mail: tom@kidonpoint.com <tom@kidonpoint.com>*

**Pull request closed without merging**
