### PR TITLE
Refactoring PeopleController for better performance and readability

### PR DESCRIPTION
**Pull request by yamakadi**
I refactored PeopleController in the same way as the DashboardController to improve performance and readability. I think this needs to be separated into files and logic for adding/removing associated models to contacts should be more standardized.

I also think there's need for a global account scope that'll take the account id from the logged in user and apply it as a constraint to all queries, so we can stop checking whether a model belongs to an account in every controller method. The only problem this might cause is not for the users but for the administrative sections where we need access to all accounts, not a specific one. In such cases, we can just use `withoutGlobalScopes()` and query that way. I can add it if you think it's necessary, too.

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks a lot! Looks much better indeed.

Can you update it to match master as I've changed some stuff on `Contact.php` moments ago to fix a bug on debts? Thanks

**Comment by yamakadi** [comment]
@djaiss I'll get to it in the next few hours.

If possible, I'd like to separate these controllers in another pull request, do they can be more easily tested. Would you be open to this by any chance? Separating the controllers would also allow moving out some of the code that doesn't necessarily belong in the Cobtact model.

**Comment by djaiss** [comment]
@yamakadi I agree on the splitting into multiple controllers. `PeopleController.php` is definitely way too big.

**Comment by yamakadi** [comment]
I'll send another pull request after fixing this one then.

**Comment by djaiss** [comment]
> I also think there's need for a global account scope that'll take the account id from the logged in user and apply it as a constraint to all queries, so we can stop checking whether a model belongs to an account in every controller method

YES. But perhaps in another PR? This is is already huge.

**Comment by djaiss** [comment]
❤️ 

Thanks a lot.

**Comment by yamakadi** [comment]
Sorry you had to fix the clashes. I couldn't get to a computer in time. Now I can work in the other PR.

**Comment by djaiss** [comment]
No worries!

**Pull request merged**
