### PR TITLE
fix: waitfordb.sh: only try the database 30 times, and exit if connection cannot be made

### PR DESCRIPTION
**Pull request by parkr**
Hello friends!

This is a fairly simple change. I use the official monicahq docker image (with some changes to allow me to bind to different ports) and I am very grateful for it! Thank you for shipping it and keeping it updated.

When you run the docker image (e.g. `docker run --rm monicahq/monica:latest`), it runs a Makefile by default which runs the `test-server` rule by default. This runs a `waitfordb.sh` script which verifies that the database server is up and listening. If the database server is *not* up and listening it will spin and spin and spin until you stop the container with `docker stop`. 

In an effort to be a bit nicer to my servers and not have endlessly-spinning containers, I would like to propose capping the number of `nc` attempts we make in this script. What do you think?

Thank you!

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/index.md#conventional-commits) that the project follows.

#### Other tasks
- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [ ] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [ ] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by parkr** [comment]
Signed the CLA! As a note, this is a personal contribution, not on behalf of my employer. 😄

**Comment by vladimino** [comment]
@parkr curious, why exactly 30?

**Comment by parkr** [comment]
@vladimino I chose 30 since each iteration sleeps for 1 second, and 30 seconds sounded reasonable for a timeout.

**Comment by asbiin** [comment]
@parkr nice work, thank you!

**Pull request merged**
