### PR TITLE
refactor: convert svg icons to components

### PR DESCRIPTION
**Pull request by ibrahimBougaoua**
**Hi,
I converted some svg icons code to components,
If this is ok, I will complete the rest of the icons.
Thanks.**

### CODE REVIEW

**Comment by asbiin** [comment]
@ibrahimBougaoua that's awesome! Thank you

**Comment by ibrahimBougaoua** [comment]
> @ibrahimBougaoua that's awesome! Thank you

**Ok I'll finish the rest**

**Comment by djaiss** [comment]
This is indeed, really great.

I didn't do it in the first place because I didn't want to put too much stress on the shadow DOM with too many components, but at the end of the day, it doesn't really matter. Vue is made for that.

**Comment by djaiss** [comment]
I couldn't commit to this branch so I "forked" it and pushed it here: #7426 

Thanks so much for your hard work!!

**Comment by ibrahimBougaoua** [comment]
Thanks.

**Pull request closed without merging**
