### PR TITLE
Default Config + APP_KEY seed

### PR DESCRIPTION
**Pull request by jeremydenoun**
- replace some constant by config value (env) especially for TimeZone & Locale
- change default APP_KEY to 32 char (avoid warning on specif openssl version) and update readme to remember 'php artisan key:generate' usage

### CODE REVIEW

**Comment by djaiss** [comment]
I agree with the comments @erdmenchen made. Can you check @jeremydenoun ?

**Comment by jeremydenoun** [comment]
It's fix @djaiss @erdmenchen

**Comment by djaiss** [comment]
Thanks a lot but I can't merge this as is.

* You've set `APP_DEFAULT_LOCALE=en` as a new ENV variable in order to replace the `locale` setting defined in `config.php`. It's ok, but the problem is that currently this variable is not used anywhere in the code, so changing it has no effect at all. Locale is actually defined at the user level (it's the `locale` value in the User table). Can you remove this change?

Apart from that, I think we are ok.

**Comment by jeremydenoun** [comment]
I think we should use it as default locale before user sign-in (especially for system mail) but this can be done in another PR

-- 
JD (iPhone)

**Comment by jeremydenoun** [comment]
done

**Comment by rabblac** [comment]
Could you add the command that generates the new key in the Docker configuration too?
You should just add this new line in https://github.com/monicahq/monica/blob/master/docker/test-server.sh
```
${ARTISAN} key:generate
```
before
```
${ARTISAN} migrate --force
```
Thanks!

**Comment by jeremydenoun** [comment]
done

**Comment by djaiss** [comment]
Sorry it took so long to review the PR. Thanks a lot for your work.

**Pull request merged**
