### PR TITLE
fix: Journal view now includes Activities as intended

### LINKED ISSUE #2423: Journal does not load
When I go to the journal view, the page is empty, it only shows that it loads content. But I can confirm with developer tools that the entries were fetched from `/journal/entries` correctly, they're just not displayed.

### PR DESCRIPTION
**Pull request by mechanarchy**
Resolves #2423. The Vue code was looking for the wrong type string, and so Activity entries never rendered.

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks a lot for your help!

**Comment by JackAction** [comment]
I still seem to have this problem.
Just created a subscription and imported my contacts. 
Created an activity:
image

But the journal does not show it, it only shows a manually created entry:
image

**Comment by sigsec** [comment]
These changes are in the code base but are not released yet; they will be in the next version after 2.12.0

**Comment by mechanarchy** [comment]
@JackAction These changes are in the code base but are not released yet; they will be in the next version after 2.12.0

**Comment by casidiablo** [comment]
I'm running `2.12.1` and still can't see activities in my journal.

**Pull request merged**
