### PR TITLE
style: Stop Activity tailoring links wrapping over line breaks

### PR DESCRIPTION
**Pull request by mgrhm**

### CODE REVIEW

**Comment by mgrhm** [comment]
I’m unsure how to fix this error. The log says:

    Error: Assets are not up to date. Please rebuild with: 'yarn run lint:all' and 'yarn run prod'.
    Error: Process completed with exit code 255.

I’ve run both of those commands and committed the updated manifest, but it’s still failing.

Any ideas?

**Review by asbiin — CHANGES_REQUESTED** [review]
These files must not be added in the sources anymore
- public/css/app-ltr.css
- public/css/app-rtl.css
- public/css/stripe.css
- public/mix-manifest.json

**Comment by mgrhm** [comment]
Reverted these changes, so this should be okay now.

**Review by mgrhm — COMMENTED** [review]
Compiled assets removed.

**Comment by asbiin** [comment]
Thank you @mgrhm !

**Pull request merged**
