### PR TITLE
gitignore composer.lock and package-lock.json from repo

### PR DESCRIPTION
**Pull request by zakriyarahman**
#### Before submitting the PR
- [ ] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [ ] If the PR is related to an issue or fix one, don't forget to indicate it.
- [ ] Make sure that the change you propose is the smallest possible.
- [ ] Screenshots are included if the PR changes the UI.
- [ ] If you change the UI, make sure the user experience is consistent with the current interface.

#### Code-related tasks
- [ ] Tests added for this feature/bug.
- [ ] Impact on the seeders.
- [ ] Impact on the API.

#### If the code changes the SQL schema
- [ ] Impact on account export.
- [ ] Impact on importing data with `vCard` and `.csv` files.
- [ ] Impact on account reset and deletion.

#### Other tasks
- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [ ] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [ ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.
- [ ] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by asbiin** [comment]
@zakriyarahman why would you want to do that ?

**Comment by zakriyarahman** [comment]
@asbiin Done. 👍

**Comment by asbiin** [comment]
@zakriyarahman I mean: we need composer.lock, and package-lock.json is the file used by npm, and we use yarn now. So adding these 2 files in .gitignore is irrelevant.

**Comment by zakriyarahman** [comment]
https://m.dotdev.co/why-the-composer-lock-file-matters-c8d1e1488be7
This answers my questions. I always thought, composer lock files are not part of the repo and should be ignored.

**Pull request closed without merging**
