### PR TITLE
Fix avatar link in journal page

### LINKED ISSUE #1438: Avatar in 'Journal' page links to nowhere
**Describe the bug**

b

### PR DESCRIPTION
**Pull request by Dagolin**
Resolves #1438

### CODE REVIEW

**Comment by asbiin** [comment]
@Dagolin the run in Circleci in your own Circleci instance isn't working (miss the SONAR context). I'm not sure why it's running in your instance...

**Comment by Dagolin** [comment]
@asbiin Interesting...I remove my instance to make sure it's running on Monica's instance, but now it keeps showing something about `asset are not up to date.`, this is what I did.

1. merge new master into branch
2. composer install /npm install
3. php artisan lang:generate
4. yarn run production

Am I missing anything?

```
Monica asset are not up to date.
Please update the Monica assets yourself by running:
 ~ php artisan lang:generate
 ~ yarn run production
```

**Comment by asbiin** [comment]
@Dagolin 

> 1. merge new master into branch
> 2. composer install /npm install
> 3. php artisan lang:generate
> 4. yarn run production

It's almost right: as we use `yarn` now, you must run `yarn install` instead of `npm install`. It might solve the problem.

**Comment by asbiin** [comment]
@Dagolin I updated the assets. Thanks

**Pull request merged**
