### PR TITLE
Remove ending periods

### PR DESCRIPTION
**Pull request by sikanderiqbal**
Remove ending periods to make data consistent with the rest of the language entries

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks so much for this, but I can't merge this as is. There are some sentences here and there that needs a "." at the end. I agree that perhaps for success messages we don't need them, or errors messages - but for sentences that appear for instance on blank pages, we need a dot at the end. Don't you agree?

**Comment by sikanderiqbal** [comment]
@djaiss I suppose it should be consistent. Which do you prefer?

**Comment by djaiss** [comment]
That's the thing. It should be consistent with the same nature of message.

* For success/errors: no dots
* For sentences that appear on blank states, or sentences for instances that are help text, a dot is necessary to end the sentence.

**Comment by sikanderiqbal** [comment]
OK, let's leave as is then. I'll remove the PR. Cheers!

**Pull request closed without merging**
