### PR TITLE
Small refactor of CSV importing

### PR DESCRIPTION
**Pull request by yamakadi**
You can use user emails now.
The validity of path and user will also be checked.

### CODE REVIEW

**Comment by djaiss** [comment]
Thanks that's great.

Could you update the README as well which mentions this feature?

**Comment by yamakadi** [comment]
I don't have any more time today, but I'm planning on expanding this with different drivers (Google, Outlook, etc.) later. It might be better to merge this now and add it to the readme then.

**Comment by djaiss** [comment]
Awesome. Thank you.

**Comment by cthurber** [comment]
Hi! Looking at working on a derivative of this function to handle importing contacts exported to CSV from LinkedIn (In undergrad, and have a lot of student connections on there I'd like to import). 

Curious if this is stable to add the button to the page similar to the existing VCard import feature?

**Comment by cthurber** [comment]
Just finished up a slight derivative of this to allow LinkedIn contact exports (CSV) to be imported as well. Import claims to be successful, and I see the rows in the database with my user id but they aren't populating for my user...

**Pull request merged**
