### PR TITLE
Fixes #1046 Bug when editing gift

### LINKED ISSUE #1046: Bug when editing gift
When a gift is edited, it stays stuck on 'Gifts offered' even when explicitly changed to one of the other two categories. The gift I'm trying to edit has all fields (except comments) filled.

### PR DESCRIPTION
**Pull request by turtles2**
This will fix #1046

### CODE REVIEW

**Comment by asbiin** [comment]
I did not see your PR when I've fixed this in #1115. Thanks

Note: Your branch seems a little confused with a lot (41) of commits. Could you clean this up for the next PR ?

**Comment by turtles2** [comment]
Yeah I just cleaned up my master. Which should resolve this going forward.
I also have another bug fix PR open. I believe you opened that bug as well.
I also added test coverage for editing in this one so may want to use that

**Comment by turtles2** [comment]
@asbiin Do you want this PR to be closed?

**Comment by asbiin** [comment]
@turtles2 thanks ! I have kept this PR for the good test you added !

**Pull request merged**
