### PR TITLE
Add validation when changing email #684

### LINKED ISSUE #684: Changing user's email address to an existing email address raises exception
* Go to Settings
* Change your email address to an email address already used by someone else
* An ugly exception is raised.

```sql
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'blank@blank.com'
 for key 'users_email_unique' (SQL: update `users` set `email` = blank@blank.com, 
`updated_at` = 2017-12-10 18:22:57 where `id` = 1)
```

### PR DESCRIPTION
**Pull request by BranTurner**
Added validation when changing your email adress to ensure the email is unique. Fixes #684.

### CODE REVIEW

**Comment by djaiss** [comment]
@BranTurner thanks so much! That's awesome. I'm going to review this probably tomorrow. I love open source 😀

**Comment by djaiss** [comment]
Awesome work. Thanks a lot!

**Comment by asbiin** [comment]
Hi ! This breaks the ability to update preferences without changes the email.
Is it normal ?
image

**Comment by djaiss** [comment]
@asbiin nope!

**Comment by djaiss** [comment]
We need to fix the fix.

**Comment by djaiss** [comment]
Actually we've fixed it https://github.com/monicahq/monica/pull/736

**Comment by asbiin** [comment]
Perfect, it was already fixed, thanks !

**Pull request merged**
