### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by djaiss**
Enjoy!

### CODE REVIEW

**Comment by asbiin** [comment]
@yarons Here I have deployed https://monica-team-pr-1070.herokuapp.com/ so you can test translations.
For Hebrew, I recently added the direction "right to left". Is it OK for you ?

**Comment by yarons** [comment]
@asbiin I started by registering and using the web interface, so far it looks good, do you want me to open another issue if I find any glitch with the new RTL style?

**Comment by yarons** [comment]
screen shot 2018-03-30 at 12 27 25

I added a contact, then tried editing the contact and editing food restrictions, this is the top bar.

**Comment by yarons** [comment]
screen shot 2018-03-30 at 12 30 36

Take a look at the icons and the buttons locations, they are overlapping the text in several ways.

I may also need your help with implementing this relatively simple solution:
In Hebrew some of the relations are simply a single letter infront of the placeholder, for example:
November - נובמבר
In November - **ב**נובמבר (Pronounced: BeNovember)
So in this case I can just use `ב%s` and it should work.
The other cases are using the same relation on an item starting with a number or a latin letter:
From GitHub - &#x202b;מ־GitHub&#x202a;
Notice there's a small minus at the top of the line? This one is called Maqqaf and when the placeholder starts with a number or a latin symbol than it should be added.
(There are several other cases handled by the code I refernced to at the bottom).

This is a very comprehensive commit message showing both the old and new approach to language prefix handling (Before this commit there was a true PHP code, after the commit there was a usage of the designated framework for prefix handling, thanks @amire80):
https://github.com/wikimedia/mediawiki/commit/6b03e2e88ec09b9886c1bf0b177de80b65dc5af5

Thanks!

**Comment by yarons** [comment]
@asbiin Another thing I've noticed is the URL field, it should always be LTR since addresses are usually in English (Well unless IDN and such, very rare cases).

screen shot 2018-03-30 at 12 58 14

**Comment by yarons** [comment]
@asbiin This happened when I tried adding a call log (The X is in the opposite direction overlapping the text):
screen shot 2018-03-30 at 13 00 21

**Comment by yarons** [comment]
@asbiin Some spacing issues when editing contact details:
screen shot 2018-03-30 at 13 02 40

(Selecting the contact age)

**Comment by yarons** [comment]
@asbiin Tag screen image should be translatable.

A single approach I can come up with is redrawing the images in HTML5 canvas and keeping the names of the tags as parameters, another option would be generating an SVG with the translated tags.

This way the image will be universal and localizable and it will be easier to maintain both LTR and RTL versions of it.

screen shot 2018-03-30 at 13 29 06

**Comment by yarons** [comment]
@asbiin This one appears in the contact list header:
screen shot 2018-03-30 at 13 33 14

**Comment by yarons** [comment]
screen shot 2018-03-30 at 13 39 27
@asbiin Slightly misaligned, also, where does the word below the number (30) is coming from? It says something like Frida instead of Friday).
Also, the word Delete remained untranslated for some reason.

**Comment by asbiin** [comment]
@yarons thank you so much !
I think it would be better to open an other issue for every translations issues, because this one is linked to crowdin (it's synced with crowdin automate).

**Comment by asbiin** [comment]
[test]
capture
tests/Browser/screenshots/failure-Tests_Browser_Settings_MultiFAControllerTest_testBarCodeContent-0.png
[id:JgShzav7PPvk3H5]

**Pull request merged**
