### PR TITLE
Yubikey support

### LINKED ISSUE #825: 2FA Support U2F devices
Linked to #164 

We should support U2F devices, like Yubikey.
This was suggested by @alrik11es

See https://github.com/Firehed/u2f-php

### PR DESCRIPTION
**Pull request by asbiin**
Close #825

#### Before submitting the PR
- [X] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [X] If the PR is related to an issue or fix one, don't forget to indicate it.
- [X] Make sure that the change you propose is the smallest possible.
- [] Screenshots are included if the PR changes the UI.
- [X] If you change the UI, make sure the user experience is consistent with the current interface.

#### Code-related tasks
- [TODO] Tests added for this feature/bug.
- [ ] Impact on the seeders.
- [ ] Impact on the API.

#### If the code changes the SQL schema
- [ ] Impact on account export.
- [ ] Impact on importing data with `vCard` and `.csv` files.
- [ ] Impact on account reset and deletion.

#### Other tasks
- [X] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [X] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [X] If it's relevant, add the documentation about your feature in the README file.
- [ ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### CODE REVIEW

**Comment by asbiin** [comment]
This feature is blocked because of #1476 @djaiss 
https://github.com/lahaxearnaud/laravel-u2f/blob/master/src/U2f.php refers to "App\User" directly.

**Comment by djaiss** [comment]
@asbiin awesome!

**Comment by asbiin** [comment]
@evaryont 
> Firefox 60 and later: Nothing, it just works out of the box.
Except it does not, on my computer ...

**Comment by evaryont** [comment]
@asbiin Oh, after looking at the Javascript I believe that's because you are using the U2F JS API. Firefox implemented the [WebAuthN specification](https://www.w3.org/TR/webauthn/) instead of it, which is more general. I believe Chrome supports WebAuthN as well, though Google's login services still rely on the older U2F API.

**Comment by asbiin** [comment]
@evaryont thanks ! I was not aware of this new API. I will try using it.

**Comment by asbiin** [comment]
@evaryont I will merge this right now, and we will implement WebAuthn later, see #1536. Thanks for the help!

**Pull request merged**
