### PR TITLE
refactor: fix bad return types with Psalter

### PR DESCRIPTION
**Pull request by muglug**
Psalm comes with a tool called Psalter that fixes issues in your codebase.

I ran

```
vendor/bin/psalter --issues=InvalidReturnType --safe-types=true
```

with a few small manual adjustments.

### CODE REVIEW

**Comment by asbiin** [comment]
Thank you @muglug !
What's wrong with all the `@return \Illuminate\Http\Response` ? It should be right from what I saw.

**Comment by muglug** [comment]
> What's wrong with all the `@return \Illuminate\Http\Response` ? It should be right from what I saw.

In short, it's not right. For example, `\Illuminate\Http\RedirectResponse` does not extend `\Illuminate\Http\Response`

**Comment by djaiss** [comment]
Nice insights, thanks for sharing.

**Comment by asbiin** [comment]
Should we run this command on the CI to check the return type, or is the command launched with psalm?

**Comment by muglug** [comment]
@asbiin Psalm will emit an error if return types are incorrect from here on out - the PR includes a Psalm config change, which tells Psalm that two issues that were once warnings should now stop the build if Psalm encounters them: 

screen shot 2019-02-15 at 14 45 53

**Comment by asbiin** [comment]
Thansk you @muglug for this improvement!

**Comment by muglug** [comment]
You're welcome!

**Pull request merged**
