### PR TITLE
docs: fix format for a code block

### PR DESCRIPTION
**Pull request by tomgs**
HTML wasn't the right fit for markdown for the apache blocks

#### Before submitting the PR
- [ ] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [ ] If the PR is related to an issue or fix one, don't forget to indicate it.
- [ ] Make sure that the change you propose is the smallest possible.
- [ ] Screenshots are included if the PR changes the UI.
- [ ] If you change the UI, make sure the user experience is consistent with the current interface.

#### Code-related tasks
- [ ] Tests added for this feature/bug.
- [ ] Impact on the seeders.
- [ ] Impact on the API.

#### If the code changes the SQL schema
- [ ] Impact on account export.
- [ ] Impact on importing data with `vCard` and `.csv` files.
- [ ] Impact on account reset and deletion.

#### Other tasks
- [ ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [ ] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [ ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.
- [ ] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by djaiss** [comment]
@tomgs good catch. Thanks for the help!

**Comment by djaiss** [comment]
@asbiin did we change the keys for sonar? Tests fail at this stage.

**Comment by asbiin** [comment]
@djaiss indeed, the signature has been changed with #1403 ... I'll fix it.

**Comment by asbiin** [comment]
Build works now. @tomgs can you please sign the CLA so we can merge this fix? Thanks!

**Comment by tomgs** [comment]
I actually skipped doing it on purpose. The agreement is quite extensive -
it applies to ANY GitHub project I'm working on and not just this one,
right?

**Comment by djaiss** [comment]
@tomgs of course not, only what you've done on Monica.

**Comment by tomgs** [comment]
@djaiss All done. 
I still have the RailGun Mail API section to write there (if you recall, I re-wrote the ubuntu and linux instructions before you moved everything back to the docs folder), and am looking for some more coding to do on this - it's a great app!

Anything specifically that needs work?

**Comment by djaiss** [comment]
@tomgs sorry - I missed your comment.

It depends on what you would like to do. There are a couple of things to tackle here https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22+label%3A%22help+wanted%22 if you want to help 😀

**Comment by tomgs** [comment]
Will take a look. Also sent you an email about and idea I had about the
docs. :)

**Pull request merged**
