### PR TITLE
docs: add more detailed MailGun instructions

### PR DESCRIPTION
**Pull request by tomgs**
Can confirm this works as of 6th of June 2019.

### CODE REVIEW

**Comment by tomgs** [comment]
Do I need to do something more here? Not sure....

**Comment by asbiin** [comment]
@tomgs Nice job, I will merge it as soon as possible

**Comment by tomgs** [comment]
Sure - there seems to be some tests (semantic pull request and monicahq,monica) that are waiting for.... something

**Comment by tomgs** [comment]
Updated the branch as well while I'm at it

**Comment by asbiin** [comment]
Thanks @tomgs !

**Pull request merged**
