### PR TITLE
show time diff from when action was created to now

### PR DESCRIPTION
**Pull request by Lovatt**
Changed the way the 'Last Actions' tab shows event timestamps, at first glance it's hard to reason how long ago an action took place without counting backwards from the current date, updated to use Carbons diffForHumans.

**Before**
screen shot 2017-06-27 at 20 36 56

**After**
screen shot 2017-06-27 at 20 36 38

### CODE REVIEW

**Comment by w00p** [comment]
This does not take into consideration which language/locale you have chosen. It will always show "hours ago", and not "timer siden" in Norwegian. I think the best way would be to make a new function in the DateHelper that checks what local a user use.

**Comment by Lovatt** [comment]
@w00p good point! i've added in a call to Carbon::setLocale during the middleware check, this should sort that problem.

**Comment by w00p** [comment]
But, you are referencing to app.config, it shout be: 
`Carbon::setLocale(Auth::user()->locale);`
Its the user that sets the local.

**Comment by Lovatt** [comment]
If you look at app/Http/Middleware/CheckLocale.php, before i call Carbon::setLocale the app.locale is set using App::setLocale(Auth::user()->locale) so they are now the same thing

**Comment by djaiss** [comment]
Thanks for this PR ❤️ , it makes a lot of sense

**Pull request merged**
