### PR TITLE
Changed "your are" to "you are"

### PR DESCRIPTION
**Pull request by wreiske**
Found this while working on some i18n stuff in another project... Figured I'd contribute a quick pull-request fix.

Thanks.

### CODE REVIEW

**Comment by asbiin** [comment]
@wreiske you cannot change PT translation directly. You'll have to change then EN version first, and run `php artisan lang:generate` to build json files.

**Comment by wreiske** [comment]
> @wreiske you cannot change PT translation directly. You'll have to change then EN version first, and run `php artisan lang:generate` to build json files.

Ahh, didn't realize the file I edited was auto-generated.

**Comment by wreiske** [comment]
@asbiin I updated the pull-request. Should I also have modified the app.js? I can remove that change easily if needed.

**Comment by asbiin** [comment]
@wreiske see the last lines of https://github.com/monicahq/monica/blob/master/docs/contribute/index.md : 

> Important note: every time a string changes in a translation file, you need to regenerate all the strings so they can be made available in JS. To do this,
> 
> use `php artisan lang:generate`
> then compile all the JS assets `yarn run prod`, and commit the whole.

You should only change `resources/lang/en/settings.php` file, other lang files will be overwritten.
After running `php artisan lang:generate` and `yarn run prod`, you have to commit `en.json` and `app.js` files.

**Comment by wreiske** [comment]
Everything should be in the pull request then. All translations, updated app.js, etc.

**Comment by asbiin** [comment]
@wreiske You still need to revert every change on 'resources/lang/XX/settings.php' file, except for "en" of course, then rerun `php artisan lang:generate` and `yarn run prod`, and commit `app.js` and `public/js/langs/en.json` files.

**Comment by wreiske** [comment]
> @wreiske You still need to revert every change on 'resources/lang/XX/settings.php' file, except for "en" of course, then rerun `php artisan lang:generate` and `yarn run prod`, and commit `app.js` and `public/js/langs/en.json` files.

Yeah, I have a better understanding now of what needs to be done. I'll do a fresh commit in a few days when I get around to it. Obviously a low priority. 

Thanks.

**Pull request closed without merging**
