### PR TITLE
Fix/improve Heroku Deploy button and instructions

### PR DESCRIPTION
**Pull request by crcastle**
Hi there.  Thanks for creating Monica and adding a Heroku Deploy button.  I'm hoping to highlight this Deploy Button in Heroku's monthly newsletter for June.

Here are a few changes to the Heroku deploy instructions that I think will make it easier for others to deploy to Heroku and use.

- Fix deploy button URL (without specifying the `template=` query string variable, it looks at the referring URL which doesn't work since this button no longer lives in the root README file)
- Specify that email configuration isn't required (this confused me for a few minutes.  I didn't realize I could register the first user without having email properly setup.)
- Suggest free Mailgun add-on to setup email (Easy way to get email working for free.)

### CODE REVIEW

**Comment by djaiss** [comment]
image

Thanks so much. I'm humbled.

**Comment by crcastle** [comment]
😊 Thank *you* @djaiss for the quick merge and for creating this interesting project!  Do you have a higher quality image of the Monica logo we can use in the Heroku newsletter?  This is the only one I've found: https://github.com/monicahq/monica/blob/master/public/img/small-logo.png

**Comment by BranTurner** [comment]
@crcastle - there is a .svg file here in this repo: [https://github.com/monicahq/monicahq.github.io/tree/master/assets/img](https://github.com/monicahq/monicahq.github.io/tree/master/assets/img)

Hope this is useful!

**Comment by djaiss** [comment]
@crcastle is that ok now?

**Comment by crcastle** [comment]
Yes, thank you!

**Pull request merged**
