### PR TITLE
fix: update ignored list of currencies in CurrenciesTableSeeder with all default currencies

### LINKED ISSUE #2833: Currencies Seeder Ignore List Is Incomplete
**Describe the bug**

The currencies seeder doesn't contain all the actual default currencies. Running the seeder results in duplicates.

The defaults:
[https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2017_06_10_155349_create_currencies_data.php#L24-L30](https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2017_06_10_155349_create_currencies_data.php#L24-L30)

[https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2019_01_31_223600_add_swiss_chf_to_currencies_table.php#L14](https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2019_01_31_223600_add_swiss_chf_to_currencies_table.php#L14)

[https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2017_06_14_132911_add_zar_currency_to_currencies_table.php#L15](https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/migrations/2017_06_14_132911_add_zar_currency_to_currencies_table.php#L15)

The ignored list:
[https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/seeds/CurrenciesTableSeeder.php#L23](https://github.com/monicahq/monica/blob/9d13aded1ceb2cdbcc1fb2cbcf4887b320ddc23f/database/seeds/CurrenciesTableSeeder.php#L23)

**Screenshots**
None.

**Which version are you using:**
 - A server you maintain yourself (if so, please indicate your current version of Monica): v2.14.0

**Additional context**
I'm not a PHP dev, but couldn't [`DB::updateOrInsert`](https://laravel.com/docs/5.8/queries#updates) be used.

### PR DESCRIPTION
**Pull request by Mohammed90**
Closes #2833

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [N/A] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/master/docs/contribute/index.md#conventional-commits) that the project follows.

### Front-end changes
- [N/A] If you change the UI, make sure to ask repositories administrators first about your changes by pinging @djaiss or @asbiin in this PR.
- [N/A] Screenshots are included if the PR changes the UI.
- [N/A] Front-end tests have been written with Cypress.

#### Backend/models changes
- [N/A] The API has been updated.
- [N/A] API's documentation has been added by submitting a pull request in the [marketing website repository](https://github.com/monicahq/marketing_site/pulls).
- [N/A] Tests have been added for the new code.
- [N/A] If you change a model, make sure the FakeContentTableSeeder is updated. We need seeders to develop locally and generate fake data.

#### If the code changes the SQL schema
- [N/A] Make sure exporting account data as SQL is still working.
- [N/A] Make sure your changes do not break importing data with `vCard` and `.csv` files.
- [N/A] Make sure account reset and deletion still work.

#### Other tasks
- [x] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG.md) entry added, if necessary, under `UNRELEASED`.
- [x] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [x] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/master/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [N/A] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

**Comment by Mohammed90** [comment]
The test "Tests\Api\Settings\ApiCurrencyControllerTest::test_currency_get_all" is expecting 157, but the [JSON file](https://github.com/monicahq/monica/blob/7996efb3e0834a9907362a512c3207d6ae7c6100/database/seeds/json/2017_08_02_124102_add_world_currencies.json) contains only 153 currencies. I presume the test is wrong? Because all the currencies in the `$ignore` list are in the file and more.

**Comment by Mohammed90** [comment]
Any chance this gets reviewed and, hopefully, merged?

**Comment by asbiin** [comment]
> Any chance this gets reviewed and, hopefully, merged?

This will be reviewed in time, after the release 2.15.0 is done.

**Comment by asbiin** [comment]
Thank you @Mohammed90 !

**Pull request merged**
